# If the plugin will create a separate world for the games (otherwise uses default world)
use-separate-world: true
# biomes where the game is disabled (oceans by default)
biomes-blacklist:
  - OCEAN
  - FROZEN_OCEAN
  - DEEP_OCEAN
  - WARM_OCEAN
  - LUKEWARM_OCEAN
  - COLD_OCEAN
  - DEEP_WARM_OCEAN
  - DEEP_LUKEWARM_OCEAN
  - DEEP_COLD_OCEAN
  - DEEP_FROZEN_OCEAN

# size of the border (better below 3000 otherwise games would overlap)
border: 500

default-scenario: rarities2

config-version: 2.2 # Don't touch this